# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Orbit demo app"
  lane :betaOrbit do

    match(
      api_key_path: "fastlane/apple_connect_auth.json",
      type: "appstore",
    )

    # increment_build_number(
    #   build_number: latest_testflight_build_number + 1
    # )

    update_project_team(
      path: "Projects/Orbit/Orbit.xcodeproj",
      teamid: ENV["TEAM_ID"]
    )

    build_app(
      scheme: "Orbit-Debug",
      workspace: "OrbitWorkspace.xcworkspace"
    )
    
    upload_to_testflight(
      app_identifier: "com.yaf.orbit",
      api_key_path: "fastlane/apple_connect_auth.json"
    )

  end

  desc "On boarding demo app"
  lane :betaOnboarding do

    match(
      api_key_path: "fastlane/apple_connect_auth.json",
      type: "appstore",
    )

    # increment_build_number(
    #   build_number: latest_testflight_build_number + 1
    # )

    update_project_team(
      path: "Projects/Feature/Onboarding/FeatureOnboarding.xcodeproj",
      teamid: ENV["TEAM_ID"]
    )

    build_app(
      scheme: "FeatureOnboardingExample-Release",
      workspace: "OrbitWorkspace.xcworkspace"
    )
    
    upload_to_testflight(
      app_identifier: "com.yaf.orbit.feature.example",
      api_key_path: "fastlane/apple_connect_auth.json"
    )

  end

  desc "Shake mission demo app"
  lane :betaShakeMission do

    match(
      api_key_path: "fastlane/apple_connect_auth.json",
      type: "appstore",
    )

    # increment_build_number(
    #   build_number: latest_testflight_build_number + 1
    # )

    update_project_team(
      path: "Projects/Feature/AlarmMission/AlarmMission.xcodeproj",
      teamid: ENV["TEAM_ID"]
    )

    build_app(
      scheme: "FeatureAlarmMissionExample-Release",
      workspace: "OrbitWorkspace.xcworkspace"
    )
    
    upload_to_testflight(
      app_identifier: "com.yaf.orbit.feature.example",
      api_key_path: "fastlane/apple_connect_auth.json"
    )

  end
  
end
